version: 0.2

env:
  parameter-store:
    GITHUB_TOKEN:
      "/continuous_apply/github_token"
phases:
  install:
    commnands:
      - ${CODEBUILD_SRC_DIR}/scripts/install.sh
  build:
    commnands:
      - ${CODEBUILD_SRC_DIR}/scripts/build.sh